(defun clasifico-triangulos() 
	(let ((lado1 0) (lado2 0) (lado3 0)) 
		(print "Ingrese el primer lado")
		(setq lado1 (read))
		(print "Ingrese el segundo lado")
		(setq lado2 (read))
		(print "Ingrese el tercer lado")
		(setq lado3 (read))
		(cond ((= lado1 lado2 lado3) 'Equilatero)
			((or (= lado1 lado2) (= lado1 lado3) (= lado2 lado3)) 'Isosceles)
			((or (/= lado1 lado2 lado3)) 'Escaleno))))