(defun mi-segundo() 
	(let ((lista ()) (atomo 0))
		(print "ingrese la lista de numeros")
		(setq lista (read))
		(print "ingrese el atomo") 
		(setq atomo (read))
		(if (and (consp lista) (atom atomo)) 
			(setq nuevaLista (cons (car lista) (cons atomo (cdr lista))))
			(print "Error en los valores"))))