(defun ingresarNotas()
	(let ((notas ()))
		(print "Ingrese las notas de parciales del alumno en formato lista")
		(setq notas (read))
		(if (listp notas)
			(aprobado notas)
			(print "Formato incorrecto")
		)
	)
)

(defun aprobado(notas)
	(cond
		((endp notas) t)
		((not (numberp (car notas))) (aprobado (cdr notas)))
		((>= (car notas) 4) (aprobado (cdr notas)))
		(t nil)
	)
)